# Generated by Django 5.1.7 on 2025-04-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.GenericIPAddressField(unique=True)),
                ('ProductName', models.CharField(max_length=150, unique=True)),
                ('Category', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Stock', models.IntegerField()),
                ('Brand', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
