# Generated by Django 5.1.7 on 2025-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductID',
            field=models.GenericIPAddressField(auto_created=True, unique=True),
        ),
    ]
