# Generated by Django 5.1.7 on 2025-04-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addProduct', '0002_alter_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductID',
        ),
    ]
