# Generated by Django 5.1.7 on 2025-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addProduct', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.TextField(max_length=100000),
        ),
    ]
